project_id = "multi-cloud-self-healing-agent"
region = "europe-west3"
bucket_name = "etl-pipeline-gcp-insights-data-9da821"
service_account_id = "pipelines-insights-sa"
k8s_service_account_name = "pipelines-insights-sa"