resource_group_name = "multi-cloud-agent-rg"
storage_account_name = "etlpostgrestoadls021826"
container_name = "etl-postgres-to-adls-insights-data"
project_id = "pipe_etl_postgres_to_adls_to_azure"
managed_identity_name = "multi-cloud-pipelines-identity"