apiVersion: v1
kind: Namespace
metadata:
  name: analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-mkt-insights-sa
  namespace: analytics
  annotations:
    iam.gke.io/gcp-service-account: "global-mkt-insights-sa@multi-cloud-self-healing-agent.iam.gserviceaccount.com"
