apiVersion: v1
kind: Namespace
metadata:
  name: analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-insights-sa
  namespace: analytics
  annotations:
    azure.workload.identity/client-id: "07c760a9-863c-4f34-bf50-ef2460dcc28c"
  labels:
    azure.workload.identity/use: "true"
