apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  namespace: analytics
  labels:
    project_id: multi-cloud-self-healing-agent
    component: trino
spec:
  replicas: 1
  progressDeadlineSeconds: 1800
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
        project_id: multi-cloud-self-healing-agent
        component: trino
    spec:
      serviceAccountName: us-crm-insights-sa
      containers:
      - name: trino
        image: trinodb/trino:403
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: hive-catalog
          mountPath: /etc/trino/catalog
        - name: sql-scripts
          mountPath: /scripts
      volumes:
      - name: hive-catalog
        configMap:
          name: hive-catalog-config
      - name: sql-scripts
        configMap:
          name: trino-sql-config
---
apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: analytics
  labels:
    project_id: multi-cloud-self-healing-agent
    component: trino
spec:
  selector:
    app: trino
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
