"""
Natural Language Pipeline Parser.

Converts a free-text pipeline description into a complete config bundle
(pipeline_conf, db_conf, rules_conf, infra_conf) that is structurally
identical to hand-written YAML files, so the rest of the system needs
zero changes.

Dynamic infrastructure values (ECR base URL, GCP project ID, etc.) are
read from .bootstrap_outputs.json when available — generated by:
    python scripts/export_bootstrap_outputs.py

Usage:
    from utils.nlp_parser import build_pipeline_bundle_from_nl
    pipe, db, rules, infra, pipeline_id, task = build_pipeline_bundle_from_nl(description)
"""
import json
import os
import re
import yaml
from pathlib import Path
from typing import Literal
from pydantic import BaseModel, field_validator, ValidationError
from openai import OpenAI
from dotenv import load_dotenv
from agents.constants import CONFIGS_DIR
from utils.llm_defaults import NL_MODEL

load_dotenv()
client = OpenAI()

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_BOOTSTRAP_OUTPUTS_FILE = _PROJECT_ROOT / ".bootstrap_outputs.json"


def _load_bootstrap_outputs() -> dict:
    """
    Load real infrastructure values from .bootstrap_outputs.json.
    Returns empty dict if the file does not exist (graceful degradation).
    """
    if _BOOTSTRAP_OUTPUTS_FILE.exists():
        with open(_BOOTSTRAP_OUTPUTS_FILE) as f:
            data = json.load(f)
        print(f"✅ Bootstrap outputs loaded from {_BOOTSTRAP_OUTPUTS_FILE.name}")
        return data
    print(
        f"⚠️  {_BOOTSTRAP_OUTPUTS_FILE.name} not found — using defaults.\n"
        "   Run `python scripts/export_bootstrap_outputs.py` after bootstrap to unlock real values."
    )
    return {}

# ---------------------------------------------------------------------------
# Static lookup tables
# ---------------------------------------------------------------------------

# Location keyword → cloud region
_REGION_MAP = {
    # AWS
    "frankfurt": "eu-central-1",
    "ireland": "eu-west-1",
    "london": "eu-west-2",
    "paris": "eu-west-3",
    "virginia": "us-east-1",
    "ohio": "us-east-2",
    "oregon": "us-west-2",
    "tokyo": "ap-northeast-1",
    "singapore": "ap-southeast-1",
    "sydney": "ap-southeast-2",
    # GCP
    "belgium": "europe-west1",
    "netherlands": "europe-west4",
    "zurich": "europe-west6",
    "iowa": "us-central1",
    # Azure
    "east us": "eastus",
    "west us": "westus",
    "west europe": "westeurope",
    "north europe": "northeurope",
}

# Sentinel for live-bootstrap STATE-BACKEND values that MUST come from .bootstrap_outputs.json.
# Using an obviously-fake placeholder (not a plausible-but-dead name) means a real NL-DEPLOY
# without exported bootstrap outputs fails LOUDLY + clearly, instead of erroring deep in terraform
# on a real-looking bucket that no longer exists. The build below overrides each of these from
# bootstrap outputs when present, so they are sentinels ONLY when outputs are missing — and
# _load_bootstrap_outputs already prints a warning telling the user to run
# scripts/export_bootstrap_outputs.py. (Preview shows the sentinel honestly.)
#
# NOTE: real NL-DEPLOY requires the target cloud's bootstrap to be live AND its outputs exported;
# the non-state defaults below (cluster names, registries) likewise assume the standard bootstrap
# names. NL authoring is otherwise structurally correct for the three object-storage clouds.
_REQUIRES_BOOTSTRAP = "REQUIRES_BOOTSTRAP_OUTPUTS"

# Bootstrap-level defaults — must match the names provisioned by bootstrap/*/
_CLOUD_DEFAULTS = {
    "aws": {
        "eks_cluster_name": "multi-cloud-agent-cluster",
        "state_bucket": _REQUIRES_BOOTSTRAP,   # from bootstrap outputs (else fail-loud)
        "lock_table": _REQUIRES_BOOTSTRAP,     # from bootstrap outputs (else fail-loud)
        "default_region": "eu-central-1",
        "trino_catalog": "hive",
    },
    "azure": {
        "aks_cluster_name": "multi-cloud-agent-aks",
        "acr_login_server": "mcselfhealagentacr.azurecr.io",
        "resource_group_name": "multi-cloud-agent-rg",
        "state_storage_account": _REQUIRES_BOOTSTRAP,  # from bootstrap outputs (else fail-loud)
        "state_container": "tfstate",
        "subscription_id_env": "AZURE_SUBSCRIPTION_ID",
        "default_region": "westeurope",
        "trino_catalog": "hive",
    },
    "gcp": {
        "gke_cluster_name": "multi-cloud-agent-gke",
        "state_bucket": _REQUIRES_BOOTSTRAP,   # from bootstrap outputs (else fail-loud)
        "artifact_registry_region": "europe-west3",
        "artifact_registry_repo": "multi-cloud-agent-repo",
        "project_id_env": "GCP_PROJECT_ID",
        "default_region": "europe-west3",
        "trino_catalog": "hive",
    },
}

# Common domain → Trino schema name
_SCHEMA_MAP = {
    "sales": "sales_eu",
    "crm": "crm_us",
    "marketing": "marketing_global",
    "finance": "finance",
    "hr": "hr",
    "logistics": "logistics",
}

# cloud → the static infra config FILE name under configs/infra/. NOT a uniform "<cloud>_bucket":
# azure's file is azure_blob.yaml (aws's is aws_s3.yaml). A wrong name makes the generated bundle's
# target_infra_config point at a non-existent file → load_pipeline_bundle fails for a NL pipeline.
_INFRA_CONFIG_NAME = {"aws": "aws_s3", "azure": "azure_blob", "gcp": "gcp_bucket"}

# Infra conf templates — mimic the existing infra YAML files
_INFRA_CONF = {
    "aws": {
        "infrastructure_type": "object_storage",
        "cloud_provider": "aws",
        "service_name": "s3_bucket",
        "data_format": "parquet",
        "compression_type": "snappy",
        "auth_method": "aws_iam_oidc_irsa",
        "object_ownership": "BucketOwnerEnforced",
        "versioning_enabled": True,
    },
    "azure": {
        "infrastructure_type": "object_storage",
        "cloud_provider": "azure",
        "service_name": "blob_storage",
        "data_format": "parquet",
        "compression_type": "snappy",
        "auth_method": "azure_ad_workload_identity",
        "storage_tier": "Hot",
        "hierarchical_namespace": True,
        "versioning_enabled": True,
        "soft_delete_retention_days": 7,
    },
    "gcp": {
        "infrastructure_type": "object_storage",
        "cloud_provider": "gcp",
        "service_name": "gcs_bucket",
        "data_format": "parquet",
        "compression_type": "snappy",
        "auth_method": "gcp_workload_identity_federation",
        "uniform_bucket_level_access": True,
        "public_access_prevention": "enforced",
    },
}

# ---------------------------------------------------------------------------
# Pydantic validation model
# ---------------------------------------------------------------------------

class PipelineIntent(BaseModel):
    pipeline_slug: str
    data_domain: Literal["sales", "crm", "marketing", "finance", "hr", "logistics", "other"]
    source_db_type: Literal["postgres", "mysql", "sqlite"]
    source_table: str
    target_cloud: Literal["aws", "azure", "gcp"]
    frequency: Literal["daily", "hourly", "realtime", "weekly"] = "daily"
    owner_team: str = "analytics_team"
    business_rules: list = []

    @field_validator("pipeline_slug", "source_table")
    @classmethod
    def must_be_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must be non-empty")
        return v.strip()


# ---------------------------------------------------------------------------
# Clarification loop metadata
# ---------------------------------------------------------------------------

# Fields with fixed options → show numbered menu
FIELD_OPTIONS = {
    "target_cloud":   ["aws", "azure", "gcp"],
    "source_db_type": ["postgres", "mysql", "sqlite"],
    "data_domain":    ["sales", "crm", "marketing", "finance", "hr", "logistics", "other"],
    "frequency":      ["daily", "hourly", "realtime", "weekly"],
}

# Fields that are free text → ask open question
FIELD_QUESTIONS = {
    "source_table":  "What is the source table name?",
    "pipeline_slug": "Give a short name for this pipeline (e.g. eu_sales):",
    "owner_team":    "What is the owner team name?",
}

MAX_ROUNDS = 3

# ---------------------------------------------------------------------------
# Private clarification helpers
# ---------------------------------------------------------------------------

def _ask_field(field: str, value) -> str:
    """Interactively ask the user for a single field value."""
    if field in FIELD_OPTIONS:
        options = FIELD_OPTIONS[field]
        while True:
            print(f"\n  ❓ Choose {field}:")
            for i, opt in enumerate(options, 1):
                print(f"     {i}. {opt}")
            raw = input("  ➤ Enter number: ").strip()
            if raw.isdigit() and 1 <= int(raw) <= len(options):
                return options[int(raw) - 1]
            print(f"  ⚠️  Invalid choice — enter a number between 1 and {len(options)}.")

    if field in FIELD_QUESTIONS:
        question = FIELD_QUESTIONS[field]
        while True:
            raw = input(f"\n  ❓ {question}\n  ➤ ").strip()
            if raw:
                return raw
            print("  ⚠️  Value cannot be empty — please try again.")

    # Fallback for any other field
    while True:
        raw = input(f"\n  ❓ Enter value for '{field}':\n  ➤ ").strip()
        if raw:
            return raw
        print("  ⚠️  Value cannot be empty — please try again.")


def _validate_intent(raw: dict) -> tuple:
    """
    Attempt to construct a PipelineIntent from raw dict.
    Returns (PipelineIntent, []) on success or (None, [failed_field_names]) on failure.
    """
    try:
        intent = PipelineIntent(**raw)
        return intent, []
    except ValidationError as exc:
        failed = [e["loc"][0] for e in exc.errors() if e["loc"]]
        # Also catch missing required fields that weren't in raw at all
        required = {"pipeline_slug", "data_domain", "source_db_type", "source_table", "target_cloud"}
        missing = [f for f in required if f not in raw or raw[f] in (None, "", [])]
        all_failed = list(dict.fromkeys(failed + missing))  # deduplicate, preserve order
        return None, all_failed


def _clarification_loop(raw_intent: dict) -> PipelineIntent:
    """
    Interactively collect missing/invalid fields, up to MAX_ROUNDS attempts.
    Raises ValueError after MAX_ROUNDS failed rounds.
    """
    for round_num in range(1, MAX_ROUNDS + 1):
        intent, failed_fields = _validate_intent(raw_intent)
        if intent is not None:
            return intent

        print(f"\n  ⚠️  Missing or invalid fields (round {round_num}/{MAX_ROUNDS}): "
              f"{', '.join(failed_fields)}")
        for field in failed_fields:
            raw_intent[field] = _ask_field(field, raw_intent.get(field))

    # Final validation attempt after last round of corrections
    intent, failed_fields = _validate_intent(raw_intent)
    if intent is not None:
        return intent

    raise ValueError(
        f"❌ Could not collect valid pipeline configuration after {MAX_ROUNDS} rounds. "
        f"Still missing: {', '.join(failed_fields)}"
    )


def _handle_business_rules(raw_rules: list, domain: str) -> list:
    """
    Interactively review, edit, add, or remove business rules extracted by GPT.

    Case A — GPT returned rules: display them and enter the edit/add/remove loop.
    Case B — GPT returned no rules: offer domain suggestions, file import, or skip.

    Args:
        raw_rules: List of rule dicts extracted by _extract_intent (may be empty).
        domain:    The pipeline data domain (e.g. "sales") used for AI suggestions.

    Returns:
        Final list of rule dicts, each containing:
        rule_id, target_column, condition, action, reason.
    """

    _ACTIONS = ["DROP_RECORD", "EXCLUDE_AND_LOG", "FLAG_AS_SUSPICIOUS", "DEFAULT_VALUE"]

    def _print_rules(rules: list) -> None:
        """Print rules with 1-based numbering in a readable block format."""
        for i, r in enumerate(rules, 1):
            print(f"\n  Rule {i}: {r['rule_id']}")
            print(f"    Column    : {r['target_column']}")
            print(f"    Condition : {r['condition']}")
            print(f"    Action    : {r['action']}")
            print(f"    Reason    : {r.get('reason', '')}")

    def _ask_action() -> str:
        """Prompt user to choose an action from a numbered menu."""
        while True:
            print("\n  ❓ Choose action:")
            for i, a in enumerate(_ACTIONS, 1):
                print(f"     {i}. {a}")
            raw = input("  ➤ Enter number: ").strip()
            if raw.isdigit() and 1 <= int(raw) <= len(_ACTIONS):
                return _ACTIONS[int(raw) - 1]
            print(f"  ⚠️  Invalid choice — enter 1–{len(_ACTIONS)}.")

    def _build_rule_form(existing: dict | None = None) -> dict:
        """Guided form to create a new rule or edit an existing one."""
        existing = existing or {}
        rule_id = (
            input(f"\n  ❓ Rule ID [{existing.get('rule_id', '')}]: ").strip()
            or existing.get("rule_id", "")
        )
        col = (
            input(f"  ❓ Target column [{existing.get('target_column', '')}]: ").strip()
            or existing.get("target_column", "")
        )
        print("  ❓ Condition (pandas expression)")
        print("     Examples: df['col'].notna()  |  df['col'] > 0  |  df['col'].str.len() > 3")
        cond = (
            input(f"  [{existing.get('condition', '')}]: ").strip()
            or existing.get("condition", "")
        )
        if existing.get("action"):
            print(f"  ❓ Action — current: {existing['action']}")
        action = _ask_action()
        reason = (
            input(f"  ❓ Reason [{existing.get('reason', '')}]: ").strip()
            or existing.get("reason", "")
        )
        return {
            "rule_id": rule_id,
            "target_column": col,
            "condition": cond,
            "action": action,
            "reason": reason,
        }

    def _parse_rules_via_openai(content: str, system_msg: str) -> list:
        """Send content to OpenAI and parse the returned JSON rules array."""
        resp = client.chat.completions.create(
            model=NL_MODEL,
            temperature=0,
            messages=[
                {"role": "system", "content": system_msg},
                {"role": "user", "content": content},
            ],
        )
        raw = resp.choices[0].message.content.strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        return json.loads(raw)

    def _edit_loop(rules: list) -> list:
        """Main Keep-all / Edit / Add / Remove / Done menu loop."""
        while True:
            _print_rules(rules)
            print("\n  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
            print("  [1] Keep all")
            print("  [2] Edit a rule")
            print("  [3] Add a rule")
            print("  [4] Remove a rule")
            print("  [5] Done")
            choice = input("  ➤ ").strip()

            if choice in ("1", "5"):
                return rules

            if choice == "2":
                if not rules:
                    print("  ⚠️  No rules to edit.")
                    continue
                idx = input(f"  ❓ Edit rule number (1–{len(rules)}): ").strip()
                if idx.isdigit() and 1 <= int(idx) <= len(rules):
                    rules[int(idx) - 1] = _build_rule_form(rules[int(idx) - 1])
                else:
                    print("  ⚠️  Invalid number.")

            elif choice == "3":
                rules.append(_build_rule_form())

            elif choice == "4":
                if not rules:
                    print("  ⚠️  No rules to remove.")
                    continue
                idx = input(f"  ❓ Remove rule number (1–{len(rules)}): ").strip()
                if idx.isdigit() and 1 <= int(idx) <= len(rules):
                    removed = rules.pop(int(idx) - 1)
                    print(f"  ✅ Removed: {removed['rule_id']}")
                else:
                    print("  ⚠️  Invalid number.")

            else:
                print("  ⚠️  Invalid choice — enter 1–5.")

    # ── Case A: GPT found rules ──────────────────────────────────────────────
    if raw_rules:
        print(f"\n  🚀 {len(raw_rules)} business rule(s) extracted from your description:")
        return _edit_loop(list(raw_rules))

    # ── Case B: No rules found ───────────────────────────────────────────────
    print("\n  ⚠️  No business rules detected in your description.")
    while True:
        print("\n  [1] Suggest rules based on my domain")
        print("  [2] Load rules from a file (.md / .yaml / .json)")
        print("  [3] Continue without rules")
        choice = input("  ➤ ").strip()

        if choice == "1":
            print(f"  🚀 Requesting domain-aware rule suggestions for '{domain}'...")
            suggestions = _parse_rules_via_openai(
                content=f"Domain: {domain}",
                system_msg=(
                    f"You are a data quality expert. Suggest 3-5 business rules for a "
                    f"{domain} data pipeline. Return a JSON array only, no markdown, "
                    f"no explanation. Each item: rule_id, target_column, condition "
                    f"(pandas expression), action (one of DROP_RECORD / "
                    f"EXCLUDE_AND_LOG / FLAG_AS_SUSPICIOUS / DEFAULT_VALUE), reason."
                ),
            )
            print(f"\n  ✅ {len(suggestions)} suggestion(s) received:")
            _print_rules(suggestions)
            sel = input(
                "\n  ❓ Enter rule numbers to keep (e.g. 1,3) or 'all': "
            ).strip().lower()
            if sel == "all":
                selected = list(suggestions)
            else:
                indices = [
                    int(x.strip()) - 1
                    for x in sel.split(",")
                    if x.strip().isdigit()
                ]
                selected = [suggestions[i] for i in indices if 0 <= i < len(suggestions)]
            return _edit_loop(selected)

        if choice == "2":
            path = input("  ❓ Enter file path (.md / .yaml / .json): ").strip()
            try:
                content = open(path, encoding="utf-8").read()
            except OSError as exc:
                print(f"  ⚠️  Cannot read file: {exc}")
                continue
            print("  🚀 Parsing rules from file...")
            loaded = _parse_rules_via_openai(
                content=content,
                system_msg=(
                    "Extract business rules from this content. Return a JSON array "
                    "only, no markdown. Each item: rule_id, target_column, condition "
                    "(pandas expression), action (one of DROP_RECORD / "
                    "EXCLUDE_AND_LOG / FLAG_AS_SUSPICIOUS / DEFAULT_VALUE), reason."
                ),
            )
            print(f"\n  ✅ {len(loaded)} rule(s) parsed from file:")
            return _edit_loop(loaded)

        if choice == "3":
            return []

        print("  ⚠️  Invalid choice — enter 1, 2, or 3.")


def _confirm_and_edit(
    intent: PipelineIntent,
    business_rules: list,
) -> tuple:
    """
    Display a full pipeline configuration summary and ask for confirmation.

    Supports:
      - "yes"              → return (intent, business_rules)
      - "no"               → raise SystemExit
      - "edit <field>"     → re-prompt that field inline, then re-show summary
      - "edit business_rules" → re-run _handle_business_rules, then re-show summary

    Args:
        intent:         Validated PipelineIntent instance.
        business_rules: Current list of rule dicts (may be empty).

    Returns:
        Tuple of (PipelineIntent, list[dict]) after confirmation.
    """
    while True:
        rules_count = len(business_rules)

        print("\n  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        print("  Pipeline Configuration Summary")
        print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        print(f"  Name      : {intent.pipeline_slug:<30} [edit]")
        print(f"  Domain    : {intent.data_domain:<30} [edit]")
        db_cell = f"{intent.source_db_type}  →  table: {intent.source_table}"
        print(f"  Database  : {db_cell:<38} [edit]")
        print(f"  Cloud     : {intent.target_cloud:<30} [edit]")
        print(f"  Frequency : {intent.frequency:<30} [edit]")
        print(f"  Owner     : {intent.owner_team:<30} [edit]")
        if business_rules:
            print(f"  Business Rules ({rules_count}):                        [edit]")
            for i, r in enumerate(business_rules, 1):
                print(f"  {i}. {r['rule_id']}")
                print(f"     column: {r['target_column']}  |  {r['action']}")
        else:
            print(f"  Business Rules : {'none':<32} [edit]")
        print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

        answer = input("  Confirm? [yes / no / edit <field>]: ").strip().lower()

        if answer == "yes":
            print("  ✅ Configuration confirmed.")
            return intent, business_rules

        if answer == "no":
            raise SystemExit("  Pipeline creation cancelled.")

        if answer.startswith("edit "):
            field = answer[5:].strip()

            if field == "business_rules":
                business_rules = _handle_business_rules(business_rules, intent.data_domain)
                continue

            editable = set(FIELD_OPTIONS) | set(FIELD_QUESTIONS)
            if field not in editable:
                all_editable = sorted(editable | {"business_rules"})
                print(f"  ⚠️  Unknown field '{field}'. Editable fields: {', '.join(all_editable)}")
                continue
            new_value = _ask_field(field, getattr(intent, field, None))
            intent = intent.model_copy(update={field: new_value})
            continue

        print("  ⚠️  Invalid response. Type 'yes', 'no', or 'edit <field>'.")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s_-]", "", text)
    text = re.sub(r"[\s-]+", "_", text)
    return text[:30].strip("_")


def _infer_region(description: str, cloud: str) -> str:
    desc = description.lower()
    for keyword, region in _REGION_MAP.items():
        if keyword in desc:
            return region
    return _CLOUD_DEFAULTS[cloud]["default_region"]


def _destination_uri(cloud: str, cloud_setup: dict) -> str:
    if cloud == "aws":
        return f"s3://{cloud_setup['bucket_name']}/processed/"
    elif cloud == "gcp":
        return f"gs://{cloud_setup['bucket_name']}/processed/"
    else:
        c = cloud_setup["container_name"]
        a = cloud_setup["storage_account_name"]
        return f"abfss://{c}@{a}.dfs.core.windows.net/processed/"


def _resource_names(slug: str, cloud: str, cloud_outputs: dict) -> dict:
    """
    Generate cloud resource names from the pipeline slug.
    Uses bootstrap outputs where available for values that require
    infrastructure knowledge (account IDs, project IDs, etc.).
    """
    dash = slug.replace("_", "-")
    if cloud == "aws":
        return {
            "bucket_name": f"{dash}-insights-data",
            "ecr_repository_name": f"{dash}-pipeline-repo",
            "iam_role_name": f"{dash}-insights-role",
            "k8s_service_account_name": f"{dash}-insights-sa",
            "state_key": f"terraform/{dash}-insights/terraform.tfstate",
        }
    elif cloud == "azure":
        acct = re.sub(r"[^a-z0-9]", "", slug)[:20] + "storage"
        acct = acct[:24]
        return {
            "storage_account_name": acct,
            "container_name": f"{dash}-insights-data",
            "managed_identity_name": f"{dash}-insights-identity",
            "k8s_service_account_name": f"{dash}-insights-sa",
            "state_key": f"azure/{dash}-insights/terraform.tfstate",
        }
    else:  # gcp
        sa_id = f"{dash[:20]}-sa"
        project_id = cloud_outputs.get("project_id")
        sa_email = (
            f"{sa_id}@{project_id}.iam.gserviceaccount.com"
            if project_id
            else f"{sa_id}@<GCP_PROJECT_ID>.iam.gserviceaccount.com"
        )
        return {
            "bucket_name": f"{dash}-insights-data",
            "service_account_id": sa_id,
            "service_account_email": sa_email,
            "k8s_service_account_name": f"{dash}-insights-sa",
            "state_prefix": f"gcp/{dash}-insights/terraform.tfstate",
        }

# ---------------------------------------------------------------------------
# OpenAI intent extraction
# ---------------------------------------------------------------------------

_EXTRACTION_PROMPT = """\
You are a data engineering intent parser. Extract a structured pipeline
configuration from a natural language description.

Return a JSON object with EXACTLY these fields (no extra keys):
{
  "is_pipeline_request": true,
  "rejection_reason": "",
  "pipeline_slug": "short_name_no_spaces",
  "data_domain": "sales|crm|marketing|finance|hr|logistics|other",
  "source_db_type": "postgres|mysql|sqlite",
  "source_table": "table_name_in_snake_case",
  "target_cloud": "aws|azure|gcp",
  "frequency": "daily|hourly|realtime|weekly",
  "owner_team": "team_name_no_spaces",
  "business_rules": [
    {
      "rule_id": "snake_case_rule_name",
      "target_column": "column_name",
      "condition": "df['col'].notna()",
      "action": "DROP_RECORD|EXCLUDE_AND_LOG|FLAG_AS_SUSPICIOUS|DEFAULT_VALUE",
      "reason": "one sentence"
    }
  ]
}

Rules:
- "is_pipeline_request": true ONLY if the text describes building / ingesting / moving /
  transforming a DATA PIPELINE (a source table → a cloud destination). For anything else —
  greetings, generic questions, jokes, unrelated requests — set it to false, put a one-sentence
  "rejection_reason" explaining it is not a data-pipeline request, and leave the other fields as
  best-effort or empty. NEVER invent a plausible pipeline for clearly off-topic input.
- "to GCP" / "Google Cloud" / "BigQuery" → gcp
- "to Azure" / "Microsoft" / "ADLS" → azure
- "to AWS" / "Amazon" / "S3" / unspecified → aws
- "PostgreSQL" / "Postgres" / "RDS" / unspecified → postgres
- "MySQL" / "MariaDB" → mysql
- Any PII column (email, name, phone, ssn, address) → add FLAG_AS_SUSPICIOUS rule
- Return ONLY the JSON object, no markdown fences, no explanation."""


def _extract_intent(description: str) -> dict:
    response = client.chat.completions.create(
        model=NL_MODEL,
        temperature=0,
        messages=[
            {"role": "system", "content": _EXTRACTION_PROMPT},
            {"role": "user", "content": description},
        ],
    )
    raw = response.choices[0].message.content.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    return json.loads(raw)

# ---------------------------------------------------------------------------
# Config persistence
# ---------------------------------------------------------------------------

def _save_generated_configs(
    pipeline_id: str,
    pipe_conf: dict,
    db_conf: dict,
    rules_conf: dict,
    infra_conf: dict,
    task: str,
) -> None:
    """
    Persist generated configs to disk so the pipeline can be rerun via YAML mode.

    Writes four files (infra configs are static and never overwritten):
      1. {CONFIGS_DIR}/pipelines/{pipeline_name}_pipeline.yaml  — full pipeline config
      2. {CONFIGS_DIR}/pipelines/{pipeline_name}_objective.md   — mission objective (task)
      3. {CONFIGS_DIR}/databases/{db_type}_{pipeline_name}.yaml — database connection config
      4. {CONFIGS_DIR}/business_rules/{pipeline_name}_logic.yaml — quality rules

    Saving is best-effort: any I/O error is logged as a warning and never re-raised.

    Args:
        pipeline_id: Full pipeline identifier, e.g. ``pipe_eu_sales_to_s3``.
        pipe_conf:   Pipeline configuration dict (mirrors hand-written pipeline YAMLs).
        db_conf:     Database connection dict built by ``build_pipeline_bundle_from_nl``.
        rules_conf:  Quality-standards dict, e.g. ``{"quality_standards": [...]}``.
        infra_conf:  Cloud infrastructure dict (not saved — static files already exist).
        task:        Formatted mission-objective markdown string.
    """
    try:
        # Derive a clean pipeline name: pipe_eu_sales_to_s3 → eu_sales
        pipeline_name = re.sub(r"^pipe_", "", pipeline_id)
        pipeline_name = re.sub(r"_to_(s3|azure|gcp)$", "", pipeline_name)

        db_type = db_conf.get("db_type", "postgres")

        pipelines_dir = os.path.join(CONFIGS_DIR, "pipelines")
        databases_dir = os.path.join(CONFIGS_DIR, "databases")
        rules_dir = os.path.join(CONFIGS_DIR, "business_rules")

        for d in (pipelines_dir, databases_dir, rules_dir):
            os.makedirs(d, exist_ok=True)

        # ── 1. Pipeline YAML ─────────────────────────────────────────────
        pipeline_yaml_path = os.path.join(
            pipelines_dir, f"{pipeline_name}_pipeline.yaml"
        )
        with open(pipeline_yaml_path, "w", encoding="utf-8") as fh:
            yaml.dump(pipe_conf, fh, default_flow_style=False, allow_unicode=True)

        # ── 2. Objective markdown ─────────────────────────────────────────
        objective_path = os.path.join(
            pipelines_dir, f"{pipeline_name}_objective.md"
        )
        with open(objective_path, "w", encoding="utf-8") as fh:
            fh.write(task)

        # ── 3. Database YAML — normalise keys to match hand-written files ─
        # Generated keys look like env_var_postgres_host; existing files use env_var_host.
        db_yaml: dict = {
            "db_id": f"{db_type}_{pipeline_name}",
            "db_type": db_type,
            "connection_type": "network",
        }
        for k, v in db_conf.items():
            if k.startswith("env_var_"):
                norm_key = re.sub(rf"^env_var_{re.escape(db_type)}_", "env_var_", k)
                db_yaml[norm_key] = v
        db_yaml["default_table"] = db_conf.get("default_table", "")
        db_yaml["description"] = (
            f"Auto-generated database config for {pipeline_name}."
        )
        db_yaml_path = os.path.join(
            databases_dir, f"{db_type}_{pipeline_name}.yaml"
        )
        with open(db_yaml_path, "w", encoding="utf-8") as fh:
            yaml.dump(db_yaml, fh, default_flow_style=False, allow_unicode=True)

        # ── 4. Business-rules YAML ────────────────────────────────────────
        rules_yaml_path = os.path.join(
            rules_dir, f"{pipeline_name}_logic.yaml"
        )
        with open(rules_yaml_path, "w", encoding="utf-8") as fh:
            yaml.dump(rules_conf, fh, default_flow_style=False, allow_unicode=True)

        print(
            f"\n  ✅ Configs saved — rerun anytime with:\n"
            f"     python main.py {pipeline_name}"
        )

    except Exception as exc:  # best-effort: never crash the pipeline run
        print(f"  ⚠️  Config save failed (non-fatal): {exc}")


# ---------------------------------------------------------------------------
# Streamlit-callable helpers (no input() — safe in a web context)
# ---------------------------------------------------------------------------

def suggest_rules_for_domain(domain: str) -> list:
    """
    Call OpenAI to suggest 3-5 business rules for the given data domain.

    Returns a list of rule dicts: rule_id, target_column, condition,
    action (one of DROP_RECORD / EXCLUDE_AND_LOG / FLAG_AS_SUSPICIOUS /
    DEFAULT_VALUE), reason.
    """
    resp = client.chat.completions.create(
        model=NL_MODEL,
        temperature=0,
        messages=[
            {
                "role": "system",
                "content": (
                    f"You are a data quality expert. Suggest 3-5 business rules for a "
                    f"{domain} data pipeline. Return a JSON array only, no markdown, "
                    f"no explanation. Each item: rule_id, target_column, condition "
                    f"(pandas expression), action (one of DROP_RECORD / "
                    f"EXCLUDE_AND_LOG / FLAG_AS_SUSPICIOUS / DEFAULT_VALUE), reason."
                ),
            }
        ],
    )
    raw = resp.choices[0].message.content.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    return json.loads(raw)


def parse_rules_from_content(content: str) -> list:
    """
    Call OpenAI to extract business rules from arbitrary file content
    (.md / .yaml / .json / .txt).

    Returns a list of rule dicts with the same schema as
    ``suggest_rules_for_domain``.
    """
    resp = client.chat.completions.create(
        model=NL_MODEL,
        temperature=0,
        messages=[
            {
                "role": "system",
                "content": (
                    "Extract business rules from this content. Return a JSON array "
                    "only, no markdown. Each item: rule_id, target_column, condition "
                    "(pandas expression), action (one of DROP_RECORD / "
                    "EXCLUDE_AND_LOG / FLAG_AS_SUSPICIOUS / DEFAULT_VALUE), reason."
                ),
            },
            {"role": "user", "content": content},
        ],
    )
    raw = resp.choices[0].message.content.strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)
    return json.loads(raw)


def _build_from_answers(
    answers: dict,
    rules: list,
    description: str = "",
    cloud_override: str | None = None,
) -> tuple[dict, dict, dict, dict, str, str]:
    """
    Build the pipeline config 6-tuple from pre-validated UI answers.

    Bypasses the interactive clarification loop; suitable for Streamlit
    where field collection is done via session_state / wizard steps.

    Args:
        answers:        Dict with keys: pipeline_slug, data_domain,
                        source_db_type, source_table, target_cloud,
                        frequency, owner_team.
        rules:          Final list of rule dicts (rule_id, target_column,
                        condition, action, reason).
        description:    Original NL description (embedded in the task string
                        and used for location-based region inference).
        cloud_override: Force a specific cloud (overrides answers["target_cloud"]).

    Returns:
        pipeline_conf, db_conf, rules_conf, infra_conf, pipeline_id, task
    """
    intent = PipelineIntent(**answers)

    slug = _slugify(intent.pipeline_slug)
    cloud = cloud_override if cloud_override in ("aws", "azure", "gcp") else intent.target_cloud
    db_type = intent.source_db_type
    domain = intent.data_domain
    frequency = intent.frequency

    storage_suffix = {"aws": "s3", "azure": "azure", "gcp": "gcp"}[cloud]
    pipeline_id = f"pipe_{slug}_to_{storage_suffix}"

    all_outputs = _load_bootstrap_outputs()
    cloud_outputs = all_outputs.get(cloud, {})

    # Use description for region keyword inference; fall back to slug
    region = _infer_region(description or intent.pipeline_slug, cloud)
    res = _resource_names(slug, cloud, cloud_outputs)
    defaults = _CLOUD_DEFAULTS[cloud]
    trino_schema = _SCHEMA_MAP.get(domain, slug)
    catalog = defaults["trino_catalog"]

    cloud_setup: dict = {
        "region": region,
        "k8s_namespace": "analytics",
        **res,
        **{k: v for k, v in defaults.items() if k not in ("default_region", "trino_catalog")},
    }

    # Per-cloud bootstrap-output keys copied verbatim into cloud_setup (only when present).
    _BOOTSTRAP_KEYS = {
        "aws":   ("aws_account_id", "state_bucket", "lock_table", "eks_oidc_issuer",
                  "pipeline_irsa_role_name", "pipeline_irsa_role_arn", "oidc_provider_arn"),
        "azure": ("acr_login_server", "aks_cluster_name", "aks_oidc_issuer_url",
                  "state_storage_account", "state_container", "resource_group_name",
                  "pipeline_managed_identity_name", "pipeline_managed_identity_client_id"),
        "gcp":   ("project_id", "region", "artifact_registry_url", "state_bucket",
                  "pipeline_service_account_email", "pipeline_service_account_id"),
    }
    for k in _BOOTSTRAP_KEYS.get(cloud, ()):
        if v := cloud_outputs.get(k):
            cloud_setup[k] = v

    # AWS: a runtime-authored pipeline has no pre-created IRSA role of its own, so point
    # its ServiceAccount at the SHARED pipelines IRSA role (bootstrap, trust = StringLike
    # `system:serviceaccount:analytics:*-insights-sa`). _resource_names() set iam_role_name
    # to a per-slug `<slug>-insights-role` that does NOT exist — override it with the real
    # shared role so cloud_get() can read SSM and the pod can write S3. The SA name stays
    # `<slug>-insights-sa`, which matches the wildcard trust. (No-op for the validated YAML
    # path: that never calls _build_from_answers — it carries its own bootstrap role.)
    if cloud == "aws" and cloud_setup.get("pipeline_irsa_role_name"):
        cloud_setup["iam_role_name"] = cloud_setup["pipeline_irsa_role_name"]

    # Azure: same gap, different mechanism. The managed identity + AKS federated credential
    # are bootstrap-owned; a runtime-authored pipeline has neither. Point it at the SHARED
    # identity (its per-pipeline Terraform binds that identity to its own storage account via
    # azurerm_role_assignment, and outputs its client_id for the SA annotation). Because an
    # Azure federated-credential subject must be EXACT (no wildcard, unlike AWS IRSA), every
    # NL-authored Azure pipeline must use the one FIXED ServiceAccount name the shared
    # credential trusts — override the per-slug `<slug>-insights-sa` with it. (No-op for the
    # validated YAML path: us_crm never calls _build_from_answers.)
    if cloud == "azure" and cloud_setup.get("pipeline_managed_identity_name"):
        cloud_setup["managed_identity_name"] = cloud_setup["pipeline_managed_identity_name"]
        cloud_setup["k8s_service_account_name"] = "pipelines-insights-sa"

    # GCP: same as Azure. The GCP service account + GKE Workload Identity binding are
    # bootstrap-owned; a runtime-authored pipeline has neither. Point it at the SHARED SA (its
    # per-pipeline Terraform binds that SA to its own bucket; project-level objectAdmin already
    # covers it). A GCP WI binding member is EXACT (no wildcard), so every NL-authored GCP
    # pipeline uses the one FIXED KSA the shared binding trusts — override the per-slug SA id,
    # email and KSA. (No-op for the validated YAML path: global_marketing never calls this.)
    if cloud == "gcp" and cloud_setup.get("pipeline_service_account_id"):
        cloud_setup["service_account_id"] = cloud_setup["pipeline_service_account_id"]
        cloud_setup["service_account_email"] = cloud_setup["pipeline_service_account_email"]
        cloud_setup["k8s_service_account_name"] = "pipelines-insights-sa"

    pipeline_conf = {
        "pipeline_id": pipeline_id,
        "owner": intent.owner_team,
        "project_name": f"{slug.replace('_', '-')}-insights",
        "project_folder_name": "multi-cloud-self-healing-agent",
        "source_config": f"configs/databases/{db_type}_{slug}.yaml",
        "business_rules_config": f"configs/business_rules/{slug}_logic.yaml",
        "target_infra_config": f"configs/infra/{_INFRA_CONFIG_NAME[cloud]}.yaml",
        "project_structure": {
            "python_dir": "scripts",
            "sql_dir": "sql",
            "data_dir": "data",
            "requirements_path": "requirements.txt",
            "trino_setup_path": "sql/setup_trino.sql",
            "monitoring_path": "dashboards/monitoring_specs.json",
            "python_script_path": f"scripts/{pipeline_id}.py",
        },
        "shared_services": {
            "trino": {
                "host": "trino.analytics.svc.cluster.local",
                "port": 8080,
                "catalog": catalog,
                "schema": trino_schema,
                "table_name": pipeline_id,
            },
            "grafana": {
                "url": "http://grafana.monitoring.svc.cluster.local",
                "namespace": "monitoring",
            },
        },
        "data_domain": domain,
        "priority": "high",
        "update_frequency": frequency,
        "cloud_provider": cloud,
        f"{cloud}_setup": cloud_setup,
    }

    env_prefix = {"postgres": "POSTGRES_DB", "mysql": "MYSQL_DB", "sqlite": "SQLITE"}[db_type]
    db_conf = {
        "db_type": db_type,
        "default_table": intent.source_table,
        f"env_var_{db_type}_host": f"{env_prefix}_HOST",
        f"env_var_{db_type}_port": f"{env_prefix}_PORT",
        f"env_var_{db_type}_user": f"{env_prefix}_USER",
        f"env_var_{db_type}_password": f"{env_prefix}_PASSWORD",
        f"env_var_{db_type}_name": f"{env_prefix}_NAME",
    }

    quality_standards = [
        {
            "rule_id": r["rule_id"],
            "description": r.get("reason", ""),
            "target_criteria": {
                "column": r["target_column"],
                "condition": r["condition"],
            },
            "on_failure_action": r["action"],
        }
        for r in rules
    ]
    rules_conf = {"quality_standards": quality_standards}
    infra_conf = _INFRA_CONF[cloud].copy()

    dest_uri = _destination_uri(cloud, cloud_setup)

    nl_header = f"**Natural Language Input:** {description}\n\n---\n\n" if description else ""

    task = f"""\
# MISSION OBJECTIVE: {pipeline_id.upper()}

{nl_header}## 🏗️ 1. ARCHITECT SCOPE (DATA LOGIC)

**DATA PIPELINE (PYTHON):**
- Source: `{db_type}` database, table `{db_conf['default_table']}`
- Output format: parquet/snappy
- Destination URI: `{dest_uri}`
- Idempotency: check `{dest_uri}run_date=<today>/` before writing. If data exists, exit 0.
- Save script to: `scripts/{pipeline_id}.py`

**BUSINESS RULES:**
  - See `TRANSFORMATION_LOGIC` in your context — this is the authoritative and complete rules list. Do not infer or skip rules based on this task description.

**CATALOG & OBSERVABILITY:**
- Trino DDL: `sql/setup_trino.sql` — external table at `{dest_uri}` with `run_date` partitioning
- Trino target: `{catalog}.{trino_schema}.{pipeline_id}`
- Grafana: `dashboards/monitoring_specs.json` with 60-minute Data Silence alert

---

## 🛠️ 2. INFRA SCOPE (DEPLOYMENT & AUTOMATION)

**TERRAFORM:** Deploy {cloud.upper()} storage and identity/IAM resources.
**K8S:** Deploy namespaces, Trino, Grafana, Prometheus + Pipeline Job.
**CI/CD:** `/.github/workflows/{pipeline_id}_pipeline.yml`

---

## 🔒 3. GLOBAL CONSTRAINTS

- All DB credentials via `cloud_get()` — never `os.getenv()` for host/user/password/db. GitHub Secrets are for CI/CD auth only (ECR, cloud CLI).
- Every agent MUST query the Vector Store for domain standards before writing.
- Final signal: `echo "Deployment Complete"`.
"""

    _save_generated_configs(pipeline_id, pipeline_conf, db_conf, rules_conf, infra_conf, task)

    return pipeline_conf, db_conf, rules_conf, infra_conf, pipeline_id, task


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_pipeline_request(description: str) -> tuple[bool, str]:
    """Relevance gate for UIs (Streamlit): returns (is_pipeline_request, reason).

    True  → safe to proceed to build_pipeline_bundle_from_nl / the wizard.
    False → show `reason` to the user and stop (don't build a bogus pipeline).

    Lets a UI reject off-topic input GRACEFULLY instead of catching the ValueError that
    build_pipeline_bundle_from_nl would raise on the same input.
    """
    try:
        raw = _extract_intent(description)
    except Exception:
        return False, "Could not parse that description — please rephrase the pipeline request."
    ok = bool(raw.get("is_pipeline_request", True))
    return ok, ("" if ok else (raw.get("rejection_reason") or "Not a data-pipeline request."))


def build_pipeline_bundle_from_nl(
    description: str,
    cloud_override: str | None = None,
) -> tuple[dict, dict, dict, dict, str, str]:
    """
    Parse a natural language description and return a full config bundle.

    Args:
        description:    Free-text pipeline description.
        cloud_override: If set (e.g. "aws"), overrides the cloud inferred by GPT.

    Returns:
        pipeline_conf, db_conf, rules_conf, infra_conf, pipeline_id, task

    Raises:
        ValueError: if the description is not a data-pipeline request (relevance gate).
    """
    raw = _extract_intent(description)
    # Relevance gate — reject obvious non-pipeline input at the door instead of fabricating a
    # plausible-but-meaningless config. (The confirm step + read_data_schema are the later nets.)
    if not raw.get("is_pipeline_request", True):
        reason = raw.get("rejection_reason") or "This does not look like a data-pipeline request."
        raise ValueError(f"Not a pipeline request: {reason}")
    intent = _clarification_loop(raw)
    raw_rules = raw.get("business_rules", [])
    final_rules = _handle_business_rules(raw_rules, intent.data_domain)
    intent, final_rules = _confirm_and_edit(intent, final_rules)

    slug = _slugify(intent.pipeline_slug)
    cloud = cloud_override if cloud_override in ("aws", "azure", "gcp") else intent.target_cloud
    db_type = intent.source_db_type
    domain = intent.data_domain
    frequency = intent.frequency

    storage_suffix = {"aws": "s3", "azure": "azure", "gcp": "gcp"}[cloud]
    pipeline_id = f"pipe_{slug}_to_{storage_suffix}"

    # Load real infrastructure values from bootstrap outputs (if available)
    all_outputs = _load_bootstrap_outputs()
    cloud_outputs = all_outputs.get(cloud, {})

    region = _infer_region(description, cloud)
    res = _resource_names(slug, cloud, cloud_outputs)
    defaults = _CLOUD_DEFAULTS[cloud]
    trino_schema = _SCHEMA_MAP.get(domain, slug)
    catalog = defaults["trino_catalog"]

    # Start with bootstrap-level defaults, then override with generated names
    cloud_setup = {
        "region": region,
        "k8s_namespace": "analytics",
        **res,
        **{k: v for k, v in defaults.items() if k not in ("default_region", "trino_catalog")},
    }

    # Enrich with real bootstrap values that defaults can't know
    if cloud == "aws":
        # State bucket & lock table from real Terraform state
        if v := cloud_outputs.get("state_bucket"):
            cloud_setup["state_bucket"] = v
        if v := cloud_outputs.get("lock_table"):
            cloud_setup["lock_table"] = v
        if v := cloud_outputs.get("eks_oidc_issuer"):
            cloud_setup["eks_oidc_issuer"] = v

    elif cloud == "azure":
        # ACR, AKS, and OIDC issuer from real bootstrap
        if v := cloud_outputs.get("acr_login_server"):
            cloud_setup["acr_login_server"] = v
        if v := cloud_outputs.get("aks_cluster_name"):
            cloud_setup["aks_cluster_name"] = v
        if v := cloud_outputs.get("aks_oidc_issuer_url"):
            cloud_setup["aks_oidc_issuer_url"] = v
        if v := cloud_outputs.get("state_storage_account"):
            cloud_setup["state_storage_account"] = v
        if v := cloud_outputs.get("state_container"):
            cloud_setup["state_container"] = v
        if v := cloud_outputs.get("resource_group_name"):
            cloud_setup["resource_group_name"] = v

    elif cloud == "gcp":
        # Project ID, region, and Artifact Registry URL from real bootstrap
        if v := cloud_outputs.get("project_id"):
            cloud_setup["project_id"] = v
        if v := cloud_outputs.get("region"):
            cloud_setup["region"] = v  # override inferred region with real one
        if v := cloud_outputs.get("artifact_registry_url"):
            # Extract region and repo from the full URL for individual config keys
            # Format: "europe-west3-docker.pkg.dev/project/repo"
            cloud_setup["artifact_registry_url"] = v
        if v := cloud_outputs.get("state_bucket"):
            cloud_setup["state_bucket"] = v

    pipeline_conf = {
        "pipeline_id": pipeline_id,
        "owner": intent.owner_team,
        "project_name": f"{slug.replace('_', '-')}-insights",
        "project_folder_name": "multi-cloud-self-healing-agent",
        "source_config": f"configs/databases/{db_type}_{slug}.yaml",
        "business_rules_config": f"configs/business_rules/{slug}_logic.yaml",
        "target_infra_config": f"configs/infra/{_INFRA_CONFIG_NAME[cloud]}.yaml",
        "project_structure": {
            "python_dir": "scripts",
            "sql_dir": "sql",
            "data_dir": "data",
            "requirements_path": "requirements.txt",
            "trino_setup_path": "sql/setup_trino.sql",
            "monitoring_path": "dashboards/monitoring_specs.json",
            "python_script_path": f"scripts/{pipeline_id}.py",
        },
        "shared_services": {
            "trino": {
                "host": "trino.analytics.svc.cluster.local",
                "port": 8080,
                "catalog": catalog,
                "schema": trino_schema,
                "table_name": pipeline_id,
            },
            "grafana": {
                "url": "http://grafana.monitoring.svc.cluster.local",
                "namespace": "monitoring",
            },
        },
        "data_domain": domain,
        "priority": "high",
        "update_frequency": frequency,
        "cloud_provider": cloud,
        f"{cloud}_setup": cloud_setup,
    }

    # DB config — env var names follow the convention in tools.py:read_data_schema
    env_prefix = {"postgres": "POSTGRES_DB", "mysql": "MYSQL_DB", "sqlite": "SQLITE"}[db_type]
    db_conf = {
        "db_type": db_type,
        "default_table": intent.source_table,
        f"env_var_{db_type}_host": f"{env_prefix}_HOST",
        f"env_var_{db_type}_port": f"{env_prefix}_PORT",
        f"env_var_{db_type}_user": f"{env_prefix}_USER",
        f"env_var_{db_type}_password": f"{env_prefix}_PASSWORD",
        f"env_var_{db_type}_name": f"{env_prefix}_NAME",
    }

    # Business rules from extracted intent
    quality_standards = [
        {
            "rule_id": r["rule_id"],
            "description": r.get("reason", ""),
            "target_criteria": {
                "column": r["target_column"],
                "condition": r["condition"],
            },
            "on_failure_action": r["action"],
        }
        for r in final_rules
    ]
    rules_conf = {"quality_standards": quality_standards}

    infra_conf = _INFRA_CONF[cloud].copy()

    dest_uri = _destination_uri(cloud, cloud_setup)

    task = f"""\
# MISSION OBJECTIVE: {pipeline_id.upper()}

**Natural Language Input:** {description}

---

## 🏗️ 1. ARCHITECT SCOPE (DATA LOGIC)

**DATA PIPELINE (PYTHON):**
- Source: `{db_type}` database, table `{db_conf['default_table']}`
- Output format: parquet/snappy
- Destination URI: `{dest_uri}`
- Idempotency: check `{dest_uri}run_date=<today>/` before writing. If data exists, exit 0.
- Save script to: `scripts/{pipeline_id}.py`

**BUSINESS RULES:**
  - See `TRANSFORMATION_LOGIC` in your context — this is the authoritative and complete rules list. Do not infer or skip rules based on this task description.

**CATALOG & OBSERVABILITY:**
- Trino DDL: `sql/setup_trino.sql` — external table at `{dest_uri}` with `run_date` partitioning
- Trino target: `{catalog}.{trino_schema}.{pipeline_id}`
- Grafana: `dashboards/monitoring_specs.json` with 60-minute Data Silence alert

---

## 🛠️ 2. INFRA SCOPE (DEPLOYMENT & AUTOMATION)

**TERRAFORM:** Deploy {cloud.upper()} storage and identity/IAM resources.
**K8S:** Deploy namespaces, Trino, Grafana, Prometheus + Pipeline Job.
**CI/CD:** `/.github/workflows/{pipeline_id}_pipeline.yml`

---

## 🔒 3. GLOBAL CONSTRAINTS

- All DB credentials via `cloud_get()` — never `os.getenv()` for host/user/password/db. GitHub Secrets are for CI/CD auth only (ECR, cloud CLI).
- Every agent MUST query the Vector Store for domain standards before writing.
- Final signal: `echo "Deployment Complete"`.
"""

    _save_generated_configs(
        pipeline_id, pipeline_conf, db_conf, rules_conf, infra_conf, task
    )

    return pipeline_conf, db_conf, rules_conf, infra_conf, pipeline_id, task
