from typing import Annotated, TypedDict, List, Union
import operator
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    # The original task or mission description provided by the user
    task: str
    
    # Message history: Appends new messages to the existing list via operator.add
    messages: Annotated[List[BaseMessage], operator.add]
    
    # Stores Python code or logic generated by the Architect
    generated_code: str
    
    # Captures error logs, stack traces, or Terraform plan failures for the Medic
    error_log: str
    
    # UNIQUE IDENTIFIER for the current run
    project_id: str
    
    # Path to the master YAML configuration file
    config_path: str

    # The specific infrastructure target identified (e.g., 'aws', 'azure')
    target_infra: str
    
    # The routing decision for the LangGraph cycle
    next_step: str

    # Tracks the last non-supervisor agent that executed
    last_agent: str

    # Full configuration bundle: pipeline, database, rules, infrastructure YAMLs
    raw_configs: dict

    # List of filenames currently written to the project workspace.
    # Helps the Supervisor and Medic know the current 'file footprint'.
    written_files: List[str]

    # Boolean flag: Set to True by Infra when infrastructure is provisioned.
    # Reset to False by Medic when a fix is requested.
    infra_provisioned: bool
    
    # Tracking the specific lifecycle of the Infra Node.
    # When 'completed', the Supervisor routes directly to MEDIC.
    infra_status: str

    # Tracking the specific lifecycle of the Architect Node.
    # When 'completed', the Supervisor routes directly to INFRA.
    architect_status: str

    # Collected specifications from the Knowledge Base
    collected_specs: dict

    # True after read_data_schema has been called successfully.
    # Gates the Implementation phase — write_project_file is locked until this is True.
    schema_discovered: bool

    # Tracking the specific lifecycle of the GitHub Node.
    # When 'completed', the Supervisor routes directly to MEDIC.
    github_done: bool

    # SHA of the last commit pushed to GitHub. Used by Medic to fetch logs for the
    # exact run triggered by that push, not just the latest run in the repo.
    last_push_sha: str

    # Set to True by Medic when it requests a fix. Survives through the Architect step
    # so Infra knows it's in fix mode even though last_agent == "architect" by then.
    # Reset to False by Infra after completing the fix cycle.
    medic_fix_requested: bool

    # True if the last agent (Architect or Infra) encountered a tool error.
    # Set by the agent node; cleared to False by Supervisor when routing to Medic
    # so the next agent starts with a clean error state.
    agent_error: bool

    # Exponential-backoff counter used by Medic when CI logs are still PENDING.
    # Incremented each time Medic sleeps waiting for the CI run to complete.
    # Reset to 0 after logs arrive or a fix is requested.
    ci_poll_attempt: int